---
type: "manual"
title: "Try"
titleClass: section
linkTitle: "Try"
description: "Handle errors, execute code even if an error occurs, close resources"
tags:
  - go-script
---
<p>
    <code>try</code> is based on the similarly named construct within <code>Java</code>.
    It allows for handling errors, executing code on exit and to close resources like files automatically.
</p>

<div class="marginNote">
    If a <code>break</code> or <code>return</code> statement is executed whilst within the <code>try</code> statement
    then the <code>finally</code> statement will still be executed and any resources will be closed before they are
    passed to the containing scope.
</div>

<h3 class="paragraph">Syntax</h3>
<pre><strong>try</strong> <em>statement</em> <strong>catch(</strong> <em>variable</em> <strong>)</strong> <em>statement</em> <strong>finally</strong> <em>statement</em>
<strong>try</strong> <em>statement</em> <strong>catch(</strong> <em>variable</em> <strong>)</strong> <em>statement</em>
<strong>try</strong> <em>statement</em> <strong>finally</strong> <em>statement</em>
<strong>try</strong> <strong>(</strong> <em>resourceList</em> <strong>)</strong> <em>statement</em> <strong>catch(</strong> <em>variable</em> <strong>)</strong> <em>statement</em> <strong>finally</strong> <em>statement</em>
<strong>try</strong> <strong>(</strong> <em>resourceList</em> <strong>)</strong> <em>statement</em> <strong>catch(</strong> <em>variable</em> <strong>)</strong> <em>statement</em>
<strong>try</strong> <strong>(</strong> <em>resourceList</em> <strong>)</strong> <em>statement</em> <strong>finally</strong> <em>statement</em>
<strong>try</strong> <strong>(</strong> <em>resourceList</em> <strong>)</strong> <em>statement</em>
</pre>

<p>
    When the <code>try</code> statement is encountered, the following steps are performed:
</p>
<ol>
    <li>
        If a <em>resourceList</em> is declared then each expression within that list is evaluated in order.
        If the result implements the <code>CreateCloser</code> interface then the <code>Create()</code> function is called.
    </li>
    <li>
        The <em>statement</em> is executed.
    </li>
    <li>
        Any resources declared in the <em>resourceList</em> that implement the <code>Closer</code> or <code>CreateCloser</code> interfaces will have their
        <code>Close()</code> function called in reverse order, so the latter ones declared are closed first.
    </li>
    <li>
        If an error occurred in the <em>statement</em> and the <code>catch</code> clause is present then the named variable is created and set to the returned error.
        This error will not be passed on to the outer scope unless the <code>throw</code> function is called to re-throw it.
    </li>
    <li>
        If the <code>finally</code> clause is present it will be called.
        Even if an error occurred at any point during the statement, this will always be called.
    </li>
</ol>

<h4 class="paragraph">Resources</h4>
<p>
    When provided, the <em>resourceList</em> defines a <code>;</code> delimited list of expressions that define a resource that will be accessible from within the
    <code>try</code> statement.
</p>
<div class="marginNote">
    Although you can declare multiple resources within a <em>resourceList</em>, there is currently a bug where they are closed in the wrong order.
    Until that bug is fixed you are advised to only declare a single resource per <code>try</code> statement.
    If you need multiple resources, you will need to nest the <code>try</code> statements.
</div>
<p>
    This list is processed in sequence.
    If the result of each expression implements the <code>CreateCloser</code> interface then it will have it's <code>Create()</code> function called.
</p>
<p>
    If the result implements either of the <code>CreateCloser</code> or <code>Closer</code> interfaces, it then ensures that the <code>Close()</code> function is called
    after the main <em>statement</em> has been executed.
</p>
<p>
    These are called in reverse order so that the later resources are closed first, useful if those resources use the earlier ones, e.g. create a file, then add gzip compression
    against that file.
</p>

<h4 class="paragraph">Catch</h4>
<p>
    The <code>catch</code> clause allows for errors to be caught by the script. Without it, any error will be passed through the calling stack until it is either caught or
    cause the script to terminate.
</p>
<div class="marginNote">
    The <code>catch</code> and <code>finally</code> clauses cannot access any resources declared within the <em>resourceList</em>.
</div>
<p>
    You have to provide a variable name to store the error.
    This variable is only visible from within the statement associated with the <code>catch</code> clause.
    If you don't care about the error, just want to catch it, you can use <code>_</code> for the variable name.
    When you do this, no variable will be created and the error will not be visible to the statement.
</p>
<p>
    This statement will not have access to any variables defined within the main <em>statement</em>, including resources.
</p>

<h4 class="paragraph">Finally</h4>
<p>
    When present, the <code>finally</code> <em>statement</em> will be executed when the <code>try</code> statement terminates, regardless to if an error occurs.
</p>
<p>
    This statement will not have access to any variables defined within the main <em>statement</em>, including resources.
</p>

<h3 class="paragraph">Examples</h3>
<div class="sourceCode">// create a file. The file will be closed when try completes
try( f := os.Create( "test.txt" ) ) {
    f.WriteString( "Hello World!" )
}

// Catch an error
try {
    // This forces an error
    throw( "forced error" )
} catch( err ) {
    fmt.Println( "Caught", err )
}

// Finally clause - DO NOT USE THIS, use resources above
// it's just an example. Not only can this leave an open file handle
// the f variable is visible outside the try so you could accidentally
// access it after you have closed the resource.
f := os.Create( "test.txt" )
try {
    f.WriteString( "Hello World!" )
} finally {
    f.Close()
}
</div>

<h3 class="paragraph">Advanced example</h3>
<p>
    The <code>CreateCloser</code> interface allows for an additional pattern where you have an object created once but when referenced in a <code>try</code> statement
    you save state before the <em>statement</em> executes and restore the state afterwards.
</p>
<p>
    An example of this is in <code>go-anim</code> where a graphical context is created. When some action is done but must not change the state, then we use
    <code>try</code> to preserve the state.
</p>
<div class="sourceCode">// create a context for 4K resolution
ctx:= animGraphic.New4k()

// Now perform an action. When the try exits,
// ctx will be in the same state as before
try( ctx ) {
    gc := ctx.Gc()
    gc.SetLineWidth(10)
    gc.SetStrokeColor(stroke)
    gc.SetFillColor(stroke)
    gc.BeginPath()
    gc.ArcTo(cx,cy,radius,radius,0,2*math.Pi)
    gc.Stroke()
}
</div>
<p>
    This works because we look for the relevant interfaces on the result of the <em>resourceList</em> expression which is perfectly valid to be a variable reference.
    In this case ctx implements <code>CreateCloser</code> so it's <code>Create()</code> function is called before the statement and <code>Close()</code> afterwards.
    In its implementation, those methods save and restore it's state.
</p>
<p>
    How this works is described in the chapter explaining how to extend the language.
</p>